# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2572a89237c136691ee61aea416770e2d70d0da6844adde90b6a3867229300a361790347e3e4462e47d8f98826e01b8bf9808159093ebea805ee91a33ce394b5

test:
  secret_key_base: 3b6d1a1c3f1cb55b49068b441af95b268173e694caa3fec651bc78778965c4870b2df9b78ba233df5ad8af4a80c010814cfbd184c661a40ba773e3d33424a5ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
